version: 2.1

executors:
  go:
    parameters:
      goversion:
        type: string
    docker:
      - image: circleci/golang:<< parameters.goversion >>
    working_directory: /go/src/github.com/anthonynsimon/bild
    

commands:
  check:
    steps:
      - checkout
      - run: |
          go get ./...
          go vet ./...
          go test -v ./...

jobs:
  test_go_1_4:
    parameters: { goversion: 1.4 }
    steps: [check]
    

  test_go_1_5:
    parameters: { goversion: 1.5 }
    steps: [check]
    

  test_go_1_6:
    parameters: { goversion: 1.6 }
    steps: [check]
    

  test_go_1_7:
    parameters: { goversion: 1.7 }
    steps: [check]
    

  test_go_1_8:
    parameters: { goversion: 1.8 }
    steps: [check]
    

  test_go_1_9:
    parameters: { goversion: 1.9 }
    steps: [check]
    

  test_go_1_10:
    parameters: { goversion: 1.10 }
    steps: [check]
    

  test_go_1_11:
    parameters: { goversion: 1.11 }
    steps: [check]
    

  test_go_1_12:
    parameters: { goversion: 1.12 }
    steps: [check]
    

workflows:
  version: 2
  test:
    jobs:
      - test_go_1_4
      - test_go_1_5
      - test_go_1_6
      - test_go_1_7
      - test_go_1_8
      - test_go_1_9
      - test_go_1_10
      - test_go_1_11
      - test_go_1_12
