version: 2.1

commands:
  check:
    steps:
      - checkout
      - run: |
          go get ./...
          go vet ./...
          go test -v ./...

jobs:
  test_go_1_4:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.4
    steps: [check]
    

  test_go_1_5:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.5
    steps: [check]
    

  test_go_1_6:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.6
    steps: [check]
    

  test_go_1_7:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.7
    steps: [check]
    

  test_go_1_8:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.8
    steps: [check]
    

  test_go_1_9:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.9
    steps: [check]
    

  test_go_1_10:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.10
    steps: [check]
    

  test_go_1_11:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.11
    steps: [check]
    

  test_go_1_12:
    working_directory: /go/src/github.com/anthonynsimon/bild
    docker:
      - image: circleci/golang:1.12
    steps: [check]
    

workflows:
  version: 2
  test:
    jobs:
      - test_go_1_4
      - test_go_1_5
      - test_go_1_6
      - test_go_1_7
      - test_go_1_8
      - test_go_1_9
      - test_go_1_10
      - test_go_1_11
      - test_go_1_12
