version: 2

references:
  install-and-test: &install-and-test
    run:
      name: Install deps and run checks
      command: |
        go get ./...
        go vet ./...
        go test -v ./...

jobs:
  test:
    docker:
      - image: "circleci/golang:${CIRCLE_JOB##test-go-}"
    working_directory: /go/src/github.com/anthonynsimon/bild
    steps:
      - *install-and-test

workflows:
  version: 2
  test:
    jobs:
      - test: { name: "test-go-1.4" }
      - test: { name: "test-go-1.5" }
      - test: { name: "test-go-1.6" }
      - test: { name: "test-go-1.7" }
      - test: { name: "test-go-1.8" }
      - test: { name: "test-go-1.9" }
      - test: { name: "test-go-1.10" }
      - test: { name: "test-go-1.11" }
      - test: { name: "test-go-1.12" }
